version: "3.1"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run ${NODE_ENV}
    ports:
      - "2000:2000"
    volumes:
      - .:/usr/app/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
