version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/setup.sql

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    command: npm run ${NODE_ENV}
    ports:
      - "2000:2000"
    volumes:
      - ..:/usr/app/

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: npm run ${NODE_ENV}
    ports:
      - "3000:3000"
    volumes:
      - ..:/usr/app/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: npm run ${NODE_ENV}
    ports:
      - "3000:3000"
    volumes:
      - ..:/usr/app/
